language: cpp
compiler:
  - gcc

before_install:
  # 'python-software-properties' provides add-apt-repository
  - sudo apt-get -y install python-software-properties
  # which is needed to add the ppa that has gcc 4.8
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  # which is needed to install gcc 4.8
  - sudo apt-get -y install gcc-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  # and g++ 4.8
  - sudo apt-get -y install g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
  # grab a pre-built cmake 2.8.12 from s3
  - wget https://s3.amazonaws.com/kylo_sandbox/cmake_install.tar.bz2
  - tar xjvf cmake_install.tar.bz2 --strip 1 -C $HOME
  # Install dependencies of cfacter
  - sudo apt-get -y install libboost-filesystem1.48-dev libboost-program-options1.48-dev liblog4cxx10-dev
  - wget https://re2.googlecode.com/files/re2-20140304.tgz -O $HOME/re2-20140304.tgz
  - pushd $HOME && tar xzf re2-20140304.tgz && cd $HOME/re2 && make > /dev/null && sudo make install > /dev/null && popd

script: ./scripts/travis_target.sh

env:
  - TRAVIS_TARGET=CPPLINT
  - TRAVIS_TARGET=RELEASE
  - TRAVIS_TARGET=DEBUG
