install:
  - ps: choco install 7zip.commandline
  - ps: choco install ruby -Version 2.0.0.57600
  - ps: choco install mingw -Version 4.8.3
  - ps: $env:PATH = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
  - ps: mkdir -force C:\tools

  - ps: (New-Object net.webclient).DownloadFile('https://s3.amazonaws.com/kylo-pl-bucket/boost_1_55_0-mingw-w64_4.8.3_posix_sjlj.7z', "$pwd\boost.7z")
  - ps: 7za x boost.7z | FIND /V "ing  "
  - ps: mv boost_1_55_0-mingw-w64_4.8.3_posix_sjlj C:\tools\boost

  - ps: (New-Object net.webclient).DownloadFile('https://s3.amazonaws.com/kylo-pl-bucket/yaml-cpp-0.5.1-mingw-w64_4.8.3_posix_sjlj.7z', "$pwd\yamlcpp.7z")
  - ps: 7za x yamlcpp.7z | FIND /V "ing  "
  - ps: mv yaml-cpp-0.5.1-mingw-w64_4.8.3_posix_sjlj C:\tools\yamlcpp

build_script:
  - ps: mv "C:\Program Files (x86)\Git\bin\sh.exe" "C:\Program Files (x86)\Git\bin\shxx.exe"
  - ps: cmake -G "MinGW Makefiles" -DBOOST_ROOT=C:\tools\boost -DYAMLCPP_ROOT=C:\tools\yamlcpp -DBOOST_STATIC=ON .
  - ps: mv "C:\Program Files (x86)\Git\bin\shxx.exe" "C:\Program Files (x86)\Git\bin\sh.exe"
  - ps: mingw32-make all_unity

test_script:
  - ps: ctest -V 2>&1 | c++filt
